### ISSUE TITLE
Hackage Package

### ISSUE THREAD

**Issue by agrafix** [ewestern/haskell-postgis#2]
Any plans to make a hackage packages out of this? I'd be very interested.

**Comment by ajnsit** [comment]
Yup! We definitely need a hackage package for this.

**Comment by hce** [comment]
Any update on this? =)

**Comment by hce** [comment]
I'd be willing to maintain the package on hackage and also on stackage if you don't have time to do it...

**Comment by ewestern** [comment]
Hey, Sorry about missing this thread. 
If someone wants to maintain it, I'm open. 

One other consideration: For parsing PostGIS bytestrings, I've actually been using this: https://github.com/ewestern/geos, as it has some performance advantages, as well as coming with all the other GEOS utilities. Obviously, all the ffi calls make that one a little less stable and portable. Just FYI.

@hce Go for it, if you're up for it.

**Comment by ewestern** [comment]
http://hackage.haskell.org/package/haskell-postgis

**Comment by hce** [comment]
Hi, I'm sorry for the very late reply. I had completely forgotten about this, for $reasons. Thanks for finally closing it. :)
